#!/bin/sh

set -ev

# Delete images generated by dfsummary
rm -f docs/dfimg/*
rm -f dfimg/*

Rscript -e "bookdown::render_book('index.Rmd', 'bd.format::bs4_book')"
Rscript -e "bookdown::render_book('index.Rmd', 'bd.format::pdf_book')"
mv -f docs/_main.pdf docs/book.pdf

